### ISSUE TITLE
Non utf-8 results exception

### ISSUE THREAD

**Issue by xBeAsTx** [mher/flower#437]
If in results object we have some non utf-8 characters we get this exception:
```
[E 150728 15:51:29 web:1421] Uncaught exception GET /api/task/result/f0209a45-1b09-42b7-a284-5d4d5082b10a (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:5555', method='GET', uri='/api/task/result/f0209a45-1b09-42b7-a284-5d4d5082b10a', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': '127.0.0.1:5555', 'Accept': '*/*', 'User-Agent': 'curl/7.38.0'})
    Traceback (most recent call last):
      File "<env>\lib\site-packages\tornado\web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "<env>\lib\site-packages\tornado\web.py", line 2626, in wrapper
        return method(self, *args, **kwargs)
      File "<src>\flower\flower\api\tasks.py", line 314, in get
        self.update_response_result(response, result)
      File "<src>\flower\flower\api\tasks.py", line 51, in update_response_result
        response.update({'result': self.safe_result(result.result)})
      File "<src>\flower\flower\api\tasks.py", line 72, in safe_result
        json.dumps(result)
      File "C:\Python27\Lib\json\__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "C:\Python27\Lib\json\encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "C:\Python27\Lib\json\encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 52: invalid start byte
```

My fix would be:
```python
def safe_result(self, result):
        "returns json encodable result"
        try:
            json.dumps(result)
        except TypeError:
            return repr(result)
        except UnicodeDecodeError:
            result_reencoded = unicode(json.dumps(result, ensure_ascii=False), errors='replace').encode("ascii", "replace")
            return json.loads(result_reencoded)
        else:
            return result
```

because tornado doesn't support non utf-8 encoding too...

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/commit/ad4c47cbc36f15902decd37f5fcde3ec79ff641e

**Comment by xBeAsTx** [comment]
You fix not working. Because json.dumps raise UnicodeDecodeError not any TypeError exceptions.

**Comment by ocervell** [comment]
This is still an issue in the latest version. Please re-open.

I am using RabbitMQ as a broker and there are some special characters in my task results:
```
Traceback (most recent call last):
  File "/home/centos/.virtualenvs/monitoring/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/centos/.virtualenvs/monitoring/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
    return method(self, *args, **kwargs)
  File "/home/centos/.virtualenvs/monitoring/lib/python2.7/site-packages/flower/views/tasks.py", line 51, in get
    key=key, reverse=sort_order)
  File "/home/centos/.virtualenvs/monitoring/lib/python2.7/site-packages/flower/utils/tasks.py", line 42, in iter_tasks
    if not satisfies_search_terms(task, search_terms):
  File "/home/centos/.virtualenvs/monitoring/lib/python2.7/site-packages/flower/utils/search.py", line 49, in satisfies_search_terms
    task.args, task.kwargs, safe_str(task.result)])),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)
```

**Comment by xBeAsTx** [comment]
@mher reopen please
