### ISSUE TITLE
Flower in docker throws 500 on api request to /api/task/info/task_uuid

### ISSUE THREAD

**Issue by AndriiIsiuk** [mher/flower#942]
I have found several similar issues, but all of them seem to be fixed by now, but I am still getting the same error while calling Flower API from Docker `/api/task/info/<task_uuid>`.
Here is Traceback:
```
flower_1   | [E 191121 12:56:23 web:1670] Uncaught exception GET /api/task/info/f64a595b-a065-424c-80cb-bf897c2b9e17 (172.29.0.6)
flower_1   |     HTTPServerRequest(protocol='http', host='flower:8888', method='GET', uri='/api/task/info/f64a595b-a065-424c-80cb-bf897c2b9e17', version='HTTP/1.1', remote_ip='100.100.0.100')
flower_1   |     Traceback (most recent call last):
flower_1   |       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
flower_1   |         result = method(*self.path_args, **self.path_kwargs)
flower_1   |       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
flower_1   |         return method(self, *args, **kwargs)
flower_1   |       File "/usr/local/lib/python3.7/site-packages/flower/api/tasks.py", line 604, in get
flower_1   |         self.write(response)
flower_1   |       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 746, in write
flower_1   |         chunk = escape.json_encode(chunk)
flower_1   |       File "/usr/local/lib/python3.7/site-packages/tornado/escape.py", line 81, in json_encode
flower_1   |         return json.dumps(value).replace("</", "<\\/")
flower_1   |       File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
flower_1   |         return _default_encoder.encode(obj)
flower_1   |       File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
flower_1   |         chunks = self.iterencode(o, _one_shot=True)
flower_1   |       File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
flower_1   |         return _iterencode(o, 0)
flower_1   |       File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
flower_1   |         raise TypeError(f'Object of type {o.__class__.__name__} '
flower_1   |     TypeError: Object of type Task is not JSON serializable
```
Can you please tell what am I doning wrong? The same error is for any of `api/task/SPECIFIC_URL/<task_uuid>` Task-specific urls. But it works ok for `api/tasks` url. Is Docker version outdated or something?

**Comment by mher** [comment]
Fixed in https://github.com/mher/flower/issues/790

**Comment by benjaminh** [comment]
@mher Could you elaborate on how to solve the problem ? Looks like you have fixed it but I still get the error `TypeError: Object of type Task is not JSON serializable`. Yet, I did try to update the official docker image, but it tells me it is already up-to-date `Status: Image is up to date for mher/flower:latest`

**Comment by fabiocantone** [comment]
@mher The error still occurs
flower = 2.0.1
celery=5.3.4
docker
flower is installed via pip

uri='/api/workers'

`
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/usr/local/lib/python3.10/site-packages/flower/api/workers.py", line 183, in get
        self.write(self.application.workers)
      File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 920, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python3.10/site-packages/tornado/escape.py", line 75, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type bytes is not JSON serializable
`

**Comment by Eimis** [comment]
I am getting a similar error when querying "http://flower:5555/api/workers". The reason might be that some of my background tasks take UUIDs as a parameter, but not completely sure. Although, it should still work I presume.

```
HTTPServerRequest(protocol='http', host='flower:5555', method='GET', uri='/api/workers', version='HTTP/1.1', remote_ip='172.18.0.3')
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/jay-MATOk_fk-py3.11/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/jay-MATOk_fk-py3.11/lib/python3.11/site-packages/flower/api/workers.py", line 183, in get
    self.write(self.application.workers)
  File "/root/.cache/pypoetry/virtualenvs/jay-MATOk_fk-py3.11/lib/python3.11/site-packages/tornado/web.py", line 920, in write
    chunk = escape.json_encode(chunk)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/jay-MATOk_fk-py3.11/lib/python3.11/site-packages/tornado/escape.py", line 75, in json_encode
    return json.dumps(value).replace("</", "<\\/")
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
```

**Comment by tmtabor** [comment]
I am getting a similar "TypeError: Object of type UUID is not JSON serializable" error when querying "http://flower:5555/api/workers". My background tasks do take UUIDs as a parameter.

Using the "latest" version of the Docker image.
